#!/bin/bash

function freq {
    LC_CTYPE=C &&
    LANG=C &&
    tr '[:upper:]' '[:lower:]' |
    tr ' ' '\n' |
    sed 's/[^a-zA-ZáéíóúÁÉÍÓÚñÑ]//g' |
    sort |
    uniq -c |
    sort -nr |
    awk '{print $2,$1}'
}

function uniques {
    LC_CTYPE=C &&
    LANG=C &&
    tr ' ' '\n' |
    tr '[:upper:]' '[:lower:]' |
    sed 's/[^a-zA-ZáéíóúÁÉÍÓÚñÑ]//g' |
    sort |
    uniq
}

function diff1 {
    TMP_FILE_1=$(mktemp "/tmp/XXXXXXXX")
    TMP_FILE_2=$(mktemp "/tmp/XXXXXXXX")

    cat "$1" | uniques > "$TMP_FILE_1"
    cat "$2" | uniques > "$TMP_FILE_2"

    diff --suppress-common-lines "$TMP_FILE_1" "$TMP_FILE_2"

    rm $TMP_FILE_1
    rm $TMP_FILE_2
}
